name: Docker Hub build
on:
  push:
    branches:
      - develop
      - master
      - "release/*"
      - "feature/*"
    tags:
      - "carma-system-*"

jobs:
  streets_service_base:
    strategy:
      matrix:
        UBUNTU_CODENAME: [ focal, jammy ]
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest
      file: streets_service_base/Dockerfile
      image_name: streets_service_base-test
      tag_name_suffix: ${{ matrix.UBUNTU_CODENAME }}
      additional_build_args: |
        UBUNTU_CODENAME=${{ matrix.UBUNTU_CODENAME }}
  streets_service_base_lanelet_aware:
    needs: streets_service_base
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest
      file: streets_service_base_lanelet_aware/Dockerfile
      image_name: streets_service_base_lanelet_aware-test
      tag_name_suffix: focal
      additional_build_args: |
        UBUNTU_CODENAME=focal
  intersection_model:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest
      file: intersection_model/Dockerfile
      image_name: intersection_model-test
  message_services:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest
      file: message_services/Dockerfile
      image_name: message_services-test
  tsc_client_service:
    needs: streets_service_base
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest
      file: tsc_client_service/Dockerfile
      image_name: tsc_service-test
  scheduling_service:
    needs: streets_service_base
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest
      file: scheduling_service/Dockerfile
      image_name: scheduling_service-test
  signal_opt_service:
    needs: streets_service_base
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest
      file: signal_opt_service/Dockerfile
      image_name: signal_opt_service-test
  sensor_data_sharing_service:
    needs: streets_service_base_lanelet_aware
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest
      file: sensor_data_sharing_service/Dockerfile
      image_name: sensor_data_sharing_service-test
    
